### ISSUE TITLE
软件工具更新

### ISSUE THREAD

**Issue by julienslink** [Sandman6z/SSD_Udisk_Tool_APP#1]
感谢分享，我在软件之家下载了最新的ChipGenius_v4_21_0701，和一个urwtest_v18，如果相信我的话您可以把它俩添加进去。文件放在下面
[chipgenius+urwtest.zip](https://github.com/Sandman6z/SSD_Udisk_test_software/files/12208502/chipgenius%2Burwtest.zip)

**Comment by tswd520** [comment]
caution!!! virus inside !!!

**Comment by Sandman6z** [comment]
> 感谢分享，我在软件之家下载了最新的ChipGenius_v4_21_0701，和一个urwtest_v18，如果相信我的话您可以把它俩添加进去。文件放在下面 [chipgenius+urwtest.zip](https://github.com/Sandman6z/SSD_Udisk_test_software/files/12208502/chipgenius%2Burwtest.zip)

天呐，我居然一直没留意到这个issue，我也是刚好想着更新，才看了一下。
采取了您的建议，但是由于这个软件本身会被报毒，为了安全，我通过您的PR，但是附件还是由我从论坛获取再上传，感谢老哥！
